### ISSUE TITLE
Add auto-completion

### ISSUE THREAD

**Issue by fnky** [amio/console.js#12]
When you type in part of a command and press `TAB` it should auto complete that command

```sh
set # => TAB = SETNAME
```

If there are multiple matches, show each command which starts with given input

```sh
s # => TAB =
SAY
SETNAME
```

**Comment by amio** [comment]
Nice feature,

Well it seems this intractive needs more code than the core function, and I prefer to keep it simple.
I think console.js was meant to be like a game console, or use to add some debug utillity, easter egg,
these use cases are simple, auto-completion is nice, but not necessary, a handy `help` helper may archive same goal but more lightweight.

If in your case it is necessary, let me know :)

And besides, maybe we could add a plugin api for that?

**Comment by fnky** [comment]
Sure it would be awesome with plugin, but that also increases complexity. The idea was to replicate the console in Quake 3. It doesn't have to be anything fancy.

I did at one time implement auto completion in my own replication of a Quake console which I made a long while ago. I'll see if I can dig it up from the dust.

**Comment by amio** [comment]
Oh I got it, I was thinking about tab effect of [fish](http://fishshell.com/).
This should be simple enough:
```bash
# history commands
set # => TAB = SETNAME
```
and
```bash
# history commands
  - SAY say something
  - SETNAME set user name
s # => TAB = show those hints.
```

**Comment by amio** [comment]
btw, I can't remember how the tab works in Quake 3,
could you provide some screenshot or video or so, showing how the tab exactly acting in Quake 3?

**Comment by fnky** [comment]
When typing e.g. `sv` and tabbing it will show a list of commands and auto complete to ´sv_´, because there's multiple commands starting with `sv_`

<img width="722" alt="second" src="https://cloud.githubusercontent.com/assets/995050/9540173/ac42f04a-4d5b-11e5-9b84-ea53b253351e.png">

If continuing typing e.g. `sv_che` and a single command starts with `sv_che` it will auto complete to `sv_cheats`

<img width="717" alt="fourth" src="https://cloud.githubusercontent.com/assets/995050/9540193/e484dcfc-4d5b-11e5-8e9a-6028c3b120e7.png">

Same as the first example if typing e.g. `g_e` it will auto complete to `g_enable`, because there's multiple commands starting with `g_enable`

<img width="716" alt="sixth" src="https://cloud.githubusercontent.com/assets/995050/9540199/ffe25c40-4d5b-11e5-99c3-3bc74012f22b.png">

**Comment by amio** [comment]
:+1:

**Comment by amio** [comment]
ping @fnky See if it works as expected http://gh.amio.us/console.js/

**Comment by fnky** [comment]
@amio That works wonderfully. Nice job!
