### ISSUE TITLE
index.js:4 Uncaught ReferenceError: Console is not defined

### ISSUE THREAD

**Issue by ironchestgames** [amio/console.js#16]
Hi, I want to start off by saying: nice work! I tried it on the project page and it is just what I was looking for.

But, I can't get it to work properly with browserify (installed it through npm `"console.js": "^1.1.0",`), it tries to load the index.js and I get the error below (the first part is in my code, but the second is in console.js.)

```
Uncaught TypeError: Console is not a constructor
    at Object.192../game.js (index.js:8)
    at s (_prelude.js:1)
    at e (_prelude.js:1)
    at _prelude.js:1
192../game.js @ index.js:8
s @ _prelude.js:1
e @ _prelude.js:1
(anonymous) @ _prelude.js:1

index.js:4 Uncaught ReferenceError: Console is not defined
    at window.onload (index.js:4)
window.onload @ index.js:4
```

I'm on OS X 10.11.5, Chrome Version 55.0.2883.95 (64-bit)

**Comment by amio** [comment]
It's not a CommonJS module, so you cannot require it by now.

But sure, it should support being required as a module :)
I'll add this to TODO list.

**Comment by amio** [comment]
@ironchestgames For now, you should be able to use it like:
```javascript
require('console.js')

const Console = window.Console
```

**Comment by ironchestgames** [comment]
Hi @amio 

Thanks for responding so quickly!

I tried your suggestion above but still got errors (Uncaught ReferenceError: Console is not defined).
I also tried setting `"main": "lib/console.min.js"` in console.js/package.json, and the file loaded, but line 11 in lib/console.js `var root = this;` is not setting root to window (because `this` in that context is probably something else idk) so it still didn't work. I changed it to window and it kind of worked, but then I got more trouble with key inputs and stuff so I didn't get any further. I might look at it at a later point in time though.

**Comment by amio** [comment]
@ironchestgames Sorry for causing those inconvenience >.<

I've made an update for supporting `const Console = require('console.js')`, if you try it in anytime later, please let me know :)

**Comment by ironchestgames** [comment]
Hello! I tried it now and everything seems to work except that the stylesheet is not loaded. Am I supposed to load it separately?

**Comment by amio** [comment]
Oops, It's a bug. Should get fixed by now :P

**Comment by ironchestgames** [comment]
It works now! Perfect! Thanks a bunch for taking the time.
