### ISSUE TITLE
caseSensitive: true does not work as expected

### ISSUE THREAD

**Issue by ironchestgames** [amio/console.js#17]
Hello,

I can't get caseSensitive property to work properly. I had a short look in the code and on row 82, in the createInputListener, it seems to be doing a toLowerCase without checking caseSensitive option.

Kind Regards,

**Comment by amio** [comment]
Thanks for pointing out ;)

**Comment by amio** [comment]
This should have been fixed.
And [v2.0](https://github.com/amio/console.js/releases/tag/v2.0.0) is out, feel free to try it out :D
